name: Build & Test (8 & 21)

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/*"
  pull_request:
    branches:
      - "main"
      - "develop"
      - "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 21]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
